"""user id

Revision ID: 63453e804927
Revises: 0d4e2e4c1cca
Create Date: 2024-10-28 11:53:04.860862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63453e804927'
down_revision = '0d4e2e4c1cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
